### ISSUE TITLE
ASCII Text Fix

### ISSUE THREAD

**Issue by harens** [harens/PyPony#1]
For all files (other than the quiz.py), the ASCII text appears to be split in half

**Comment by harens** [comment]
Reason Found: This occurs since the text moves when the window size changes. The title 'Quiz', being the smallest, therefore did not appear to be affected.

**Comment by ReyOfSun** [comment]
Add me to the presentation

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION

**Comment by ReyOfSun** [comment]
ADD ME TO THE PRESENTATION
